### ISSUE TITLE
Request to flex-api.twilio.com/v1/Channels failed with status code 400

### ISSUE THREAD

**Issue by stepanenkoo** [lehel-twilio/plugin-sms#3]
Hello,

we have issue with axios request.
In logs of Function can see:
```
failed to create channel { code: 400,
  message: 'HTTP 400 Bad Request',
  more_info: 'https://www.twilio.com/docs/errors/400',
  status: 400 }
  
```
  
  ```
UnhandledPromiseRejectionWarning: Unhandled promise rejection: Error: Request failed with status code 400
    at createError (/var/task/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/var/task/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/var/task/node_modules/axios/lib/adapters/http.js:237:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _com...
```

**Comment by stepanenkoo** [comment]
The cause of issue is wrong FLEX_FLOW_SID.
You can find correct FLEX_FLOW_SID  on Flex - Messaging page Section Incoming Message Handlers it looks like FOXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
